name: deploy-docs

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js v16.x
        uses: actions/setup-node@v3
        with:
          node-version: v16.x

      - name: Install Dependencies
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.SATELLITE_ACCESS_TOKEN }}
        run: yarn install --frozen-lockfile

      - name: Build Astro App
        env:
          GITHUB_REGISTRY_TOKEN: ${{ secrets.SATELLITE_ACCESS_TOKEN }}
        run: yarn build:tty

  dispatch-sync-event:
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@v2
        with:
          repository: deta/satellite
          token: ${{ secrets.SATELLITE_ACCESS_TOKEN }}
          event-type: sync-space-docs
          